---
- name: Install docker packages
  apt:
    name:
      - docker.io
    state: present
    update_cache: true

- name: Enable and start docker
  systemd:
    name: docker
    enabled: true
    state: started

- name: Add debian user to docker group
  user:
    name: debian
    groups: docker
    append: true
